BACKUP DATABASE [Hotel] 
TO  DISK = N'D:\Sist_BD_II2021\DATABASE\BACKUP\Hotel20210423DIF.bak' 
WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'Hotel-Differential Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
